"""Add Monster model

Revision ID: 27460307982b
Revises: 
Create Date: 2025-01-09 22:48:38.026430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27460307982b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'item_pool',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.add_column('monsters', sa.Column('name', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('monsters', sa.Column('icon', sa.String(), nullable=True))
    op.drop_constraint('monsters_nombre_key', 'monsters', type_='unique')
    op.create_unique_constraint(None, 'monsters', ['name'])
    op.drop_column('monsters', 'descripcion')
    op.drop_column('monsters', 'nombre')
    op.drop_column('monsters', 'imagen')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('imagen', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('monsters', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('monsters', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monsters', type_='unique')
    op.create_unique_constraint('monsters_nombre_key', 'monsters', ['nombre'])
    op.drop_column('monsters', 'icon')
    op.drop_column('monsters', 'description')
    op.drop_column('monsters', 'name')
    op.alter_column('items', 'item_pool',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    # ### end Alembic commands ###
